### Cleaning Data Exercise: When we have missing values, outliers, inconsistent formatting, duplicates, invalid entries and etc.

In [1]:
import pandas as pd
import numpy as np

# Generating artificial sample data

np.random.seed(42) 

n = 10000  

df = pd.DataFrame({
    "OrderID": np.random.randint(1000, 2000, n), 
    "CustomerID": np.random.randint(1, 500, n),
    "Age": np.random.choice([20, 25, 30, 35, 40, None, -10], n),
    "Price": np.random.choice([10, 20, 50, 100, None, 9999], n),  
    "City": np.random.choice(["Berlin", "berlin", "BERLIN", "Munich", "munich", None, "Munchen"], n),
    "OrderDate": np.random.choice([
        "2023-01-10", "10/02/2023", "March 5 2023", None
    ], n),
    "Product": np.random.choice(["Laptop", "Phone", "Tablet", "phone ", " LAPTOP"], n),
    "Quantity": np.random.choice([1, 2, 3, 5, None, -1], n),
    "Email": np.random.choice([
        "test@gmail.com", "user@yahoo.com", "invalid_email", None
    ], n)
})

df.to_csv("real_world_dirty_data.csv", index=False)

In [2]:
#check the original unique values in a table before cleaning
df

,OrderID,CustomerID,Age,Price,City,OrderDate,Product,Quantity,Email
0,1102,442,40,20,munich,None,phone,-1,user@yahoo.com
1,1435,279,25,None,munich,March 5 2023,Laptop,None,user@yahoo.com
2,1860,251,20,20,Munich,None,Phone,3,invalid_email
3,1270,310,20,20,Berlin,10/02/2023,Phone,None,invalid_email
4,1106,208,30,20,Berlin,2023-01-10,LAPTOP,2,user@yahoo.com
...,...,...,...,...,...,...,...,...,...
9995,1914,390,35,10,None,March 5 2023,Phone,1,user@yahoo.com
9996,1209,444,25,9999,Munchen,None,Phone,2,None
9997,1740,301,35,9999,munich,2023-01-10,Laptop,None,user@yahoo.com
9998,1861,428,35,50,BERLIN,10/02/2023,Laptop,2,invalid_email


In [3]:
#check the overview of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   OrderID     10000 non-null  int32 
 1   CustomerID  10000 non-null  int32 
 2   Age         8558 non-null   object
 3   Price       8263 non-null   object
 4   City        8584 non-null   object
 5   OrderDate   7425 non-null   object
 6   Product     10000 non-null  object
 7   Quantity    8292 non-null   object
 8   Email       7456 non-null   object
dtypes: int32(2), object(7)
memory usage: 625.1+ KB


In [4]:
#check the number of missing values in each column
df.isna().sum()

OrderID          0
CustomerID       0
Age           1442
Price         1737
City          1416
OrderDate     2575
Product          0
Quantity      1708
Email         2544
dtype: int64

In [5]:
#check the statistical summary of the data
df.describe()

,OrderID,CustomerID
count,10000.000000,10000.000000
mean,1503.470600,248.579600
std,289.724434,144.146598
min,1000.000000,1.000000
25%,1250.000000,122.000000
50%,1505.500000,250.000000
75%,1757.000000,373.000000
max,1999.000000,499.000000


In [6]:
# Definition of median, mean and mode
[10, 20, 30, 40]

# median = (20 + 30) /2

[10, 20, 30, 40, 50]

# median = 30

# mean = (10 + 20 + 30 + +40 +50)/5

[10, 20, 30, 40, 50]

# mode = 30 #mode is the most frequently occurring value in a dataset. In this case, 30 appears more than any other number, making it the mode of the dataset.



[10, 20, 30, 40, 50]

In [39]:
data = [10, 20, 30, 40, 20, 1000]

#mean
mean_ = sum(data) / (len(data))
print(f"Mean : {mean_}")

#median
median_ = pd.Series(data).median()
print(f"Median : {median_}")

#mode
mode_ = pd.Series(data).mode()
print(f"Mode : {mode_}") # 0, in the result, is a Series index and mode() always returns a Series as it is just an indicator of the order which starts from 0.

Mean : 186.66666666666666
Median : 25.0
Mode : 0    20
dtype: int64


In [8]:
print(df["Age"].unique())

[40 25 20 30 -10 35 None]


In [ ]:
#clean "Age" column for non-numeric values
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"] = df["Age"].fillna(df["Age"].median()) #fillna is just to fill the missing values with the median of the column

In [40]:
print(df["Age"].unique())

[40. 25. 30. 20. 35. 10.]


In [ ]:
#clean "Price"" column for non-numeric values
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
df["Price"] = df["Price"].fillna(df["Price"].median()) #fillna is just to fill the missing values with the median of the column

In [12]:
print(df["Price"].unique())

[  20.   50. 9999.  100.   10.]


In [ ]:
#check the initial unique values in the "Quantity" column
print(df["Quantity"].unique())

[-1 None 3 2 1 5]


In [ ]:
#clean "Quantity" column for non-numeric values
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")
df["Quantity"] = df["Quantity"].fillna(0).astype(int) #fillna is just to fill the missing values with 0 and then convert the column to integer type

In [15]:
print(df["Quantity"].unique())

[-1  0  3  2  1  5]


In [ ]:
#check the initial unique values in the "City" column
print(df["City"].unique())

['munich' 'Munich' 'Berlin' 'Munchen' 'BERLIN' 'berlin' None]


In [17]:
df["City"] = df["City"].fillna("unknown") #in this time, fillna is just to fill the missing values with "unknown"

In [ ]:
#check the unique value in the "City" column after filling the missing values
print(df["City"].unique())

['munich' 'Munich' 'Berlin' 'Munchen' 'BERLIN' 'berlin' 'unknown']


In [ ]:
#check the initial unique values in the "OrderID" column
print(df["OrderID"].unique())

[1102 1435 1860 1270 1106 1071 1700 1020 1614 1121 1466 1214 1330 1458
 1087 1372 1099 1871 1663 1130 1661 1308 1769 1343 1491 1413 1805 1385
 1191 1955 1276 1160 1459 1313 1021 1252 1747 1856 1560 1474 1058 1510
 1681 1475 1699 1975 1782 1189 1957 1686 1562 1875 1566 1243 1831 1504
 1484 1818 1646 1840 1166 1273 1387 1600 1315 1013 1241 1776 1345 1564
 1897 1339 1091 1366 1454 1427 1508 1775 1942 1034 1205 1080 1931 1561
 1001 1389 1565 1105 1771 1821 1476 1702 1401 1729 1555 1161 1201 1995
 1269 1862 1815 1455 1461 1726 1251 1701 1295 1724 1719 1748 1337 1878
 1052 1791 1921 1216 1763 1187 1379 1492 1040 1156 1014 1812 1064 1838
 1520 1128 1647 1471 1062 1138 1498 1592 1391 1674 1418 1288 1378 1772
 1489 1230 1027 1134 1200 1839 1779 1929 1032 1047 1502 1406 1573 1727
 1804 1098 1683 1725 1986 1546 1960 1738 1612 1642 1768 1004 1217 1766
 1397 1870 1794 1392 1206 1857 1553 1891 1460 1690 1574 1863 1742 1240
 1563 1095 1899 1733 1654 1170 1540 1035 1524 1159 1698 1242 1085 1795
 1577 

In [ ]:
#removing duplicates
df = df.drop_duplicates(subset = "OrderID")

[1102 1435 1106 1614 1214 1087 1871 1663 1130 1343 1491 1805 1385 1313
 1021 1252 1747 1856 1560 1681 1782 1189 1957 1831 1504 1484 1818 1840
 1273 1241 1564 1897 1366 1508 1034 1001 1105 1401 1201 1726 1701 1295
 1719 1337 1878 1379 1040 1812 1647 1498 1592 1391 1418 1288 1378 1489
 1230 1134 1200 1839 1502 1727 1098 1642 1768 1004 1397 1794 1392 1553
 1891 1460 1863 1742 1899 1654 1170 1540 1524 1159 1698 1085 1645 1797
 1472 1224 1282 1627 1744 1358 1410 1676 1373 1671 1691 1829 1496 1441
 1386 1735 1402 1129 1415 1246 1202 1183 1122 1400 1279 1836 1883 1609
 1197 1751 1143 1608 1123 1325 1348 1770 1146 1147 1550 1987 1150 1414
 1297 1262 1571 1253 1452 1036 1658 1207 1053 1672 1919 1851 1111 1152
 1913 1895 1877 1705 1915 1503 1194 1687 1749 1669 1037 1229 1437 1026
 1959 1480 1515 1048 1301 1180 1992 1190 1255 1017 1792 1734 1569 1685
 1662 1638 1154 1784 1810 1245 1175 1038 1537 1866 1407 1827 1019 1971
 1470 1142 1799 1050 1195 1773 1876 1991 1822 1655 1268 1369 1635 1656
 1830 

In [21]:
print(df["Age"].unique())

[ 40.  25.  20.  30. -10.  35.]


In [ ]:
#abs function is used to get the absolute value of a number.
#abs(5) ===> 5
#abs(-5) ===> 5
#abs(0) ===> 0

df["Age"] = df["Age"].abs() #abs() function is used to convert negative values to positive values, and it leaves positive values and zero unchanged. In this case, it will convert any negative ages to their absolute values, ensuring that all ages are non-negative.
df["Age"] = df["Age"].apply(lambda x: abs(x)) # this is just another way to do the same thing as the previous above line.

C:\Users\swjun\AppData\Local\Temp\ipykernel_14056\3450696391.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].abs() #abs() function is used to convert negative values to positive values, and it leaves positive values and zero unchanged. In this case, it will convert any negative ages to their absolute values, ensuring that all ages are non-negative.
C:\Users\swjun\AppData\Local\Temp\ipykernel_14056\3450696391.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].

In [23]:
print(df["Age"].unique())

[40. 25. 20. 30. 10. 35.]


In [44]:
#remove negative values from "Quantity" column.
df["Quantity"] = df["Quantity"].abs()

In [25]:
print(df["Quantity"].unique())

[1 0 3 2 5]


In [45]:
#check the original unique values in City column first
print(df["City"].unique())

['munich' 'berlin' 'munchen' 'unknown']


In [ ]:
df["City"] = df["City"].str.lower().str.strip() #this removes leading and trailing spaces and converts all city names to lowercase.
df["City"] = df["City"].replace({"Munchen" : "munich"}) #using dictionary ({}) to replace "Munchen" with "munich"

df.loc[: , "City"] = df["City"] = df["City"].str.lower().str.strip() #This is just another way to do as the 1st line
df.loc[: , "City"] = df["City"] = df["City"].replace({"Munchen" : "munich"}) #This is just another way to do as the 2nd line

In [28]:
print(df["Product"].unique())

['phone ' 'Laptop' 'Phone' ' LAPTOP' 'Tablet']


In [47]:
df["Product"] = df["Product"].str.lower().str.strip() #this removes leading and trailing spaces and converts all product names to lowercase.

In [30]:
print(df["Product"].unique())

['phone' 'laptop' 'tablet']


In [48]:
#Fix Date (Standardize everything under "OrderDate" into one format)

df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors = "coerce")



In [49]:
print(df["OrderDate"].unique())

<DatetimeArray>
['NaT', '2023-03-05 00:00:00']
Length: 2, dtype: datetime64[ns]


In [33]:
#How to handle outliers: "Price" column has some outliers (e.g., 9999), we can remove it as it is not a realistic price for the products in our dataset.

df = df[df["Price"] <  1000] # remove rows where "Price" is greater than or equal to 1000

In [34]:
print(df["Price"].unique())

[ 20.  50. 100.  10.]


In [ ]:
#How to validate email addresses: we can use a simple regular expression pattern to check if the email addresses are in a valid format. In other words, we can check if the email contains "@" and "." characters.

df = df[df["Email"].str.contains("@", na = False)]

In [36]:
print(df["Email"].unique())

['user@yahoo.com' 'test@gmail.com']


In [ ]:
# How to create "Revenue" column. (Revenue = Price * Quantity) why do we need revenue?
# Creating Revenue is for us to analyze the total revenue generated from all orders in our dataset. By creating a "Revenue" column, we can easily calculate the total revenue for each order and then aggregate it to get insights into the overall performance of our sales.
 
df["Revenue"] = df["Price"] * df["Quantity"] #create a new column "Revenue".

In [ ]:
df #check the cleaned table with the new number of rows and columns (e.g., 10000 rows -> 420 rows), and the new "Revenue" column is added with the only acceptable values.

,OrderID,CustomerID,Age,Price,City,OrderDate,Product,Quantity,Email,Revenue
0,1102,442,40.0,20.0,munich,NaT,phone,1,user@yahoo.com,20.0
1,1435,279,25.0,50.0,munich,2023-03-05,laptop,0,user@yahoo.com,0.0
4,1106,208,30.0,20.0,berlin,NaT,laptop,2,user@yahoo.com,40.0
8,1614,34,40.0,100.0,berlin,NaT,laptop,5,test@gmail.com,500.0
11,1214,18,30.0,10.0,munich,NaT,phone,5,user@yahoo.com,50.0
...,...,...,...,...,...,...,...,...,...,...
4673,1478,16,25.0,100.0,berlin,NaT,phone,1,test@gmail.com,100.0
4821,1486,402,30.0,10.0,munich,2023-03-05,phone,2,test@gmail.com,20.0
4904,1809,173,25.0,10.0,unknown,NaT,phone,1,user@yahoo.com,10.0
4976,1527,322,30.0,10.0,munich,2023-03-05,phone,1,test@gmail.com,10.0
